language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jpgcode' ]; then cd .. && eval "mv $currentfolder generator-jpgcode" && cd generator-jpgcode; fi

